adaptive-pid-controller-c:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ simple_adaptive_pid.application ../backup_simple_adaptive_pid_ir.json

pid-controller:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ pid_controller.application ../gen/pid_controller.json

p-controller:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ p_controller.application ../gen/p_controller.json

uc1_test:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ uc1_test.application ../gen/irs/uc1_latest_30_June.json

uc1_lin_z_axis_left_arm:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ uc1_test.application ../gen/irs/uc1_lin_z_axis_arm_1.json
