uc1:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ uc1.application ../gen/irs/uc1.json

uc3_pid:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ uc3_pid.application ../gen/irs/uc3_pid.json

uc3_abag:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ uc3_abag.application ../gen/irs/uc3_abag.json

uc1_lin_z_axis_left_arm:
	@./../STSTv4/stst.sh -s "<>" -t ../models/templates/applications/ uc1.application ../gen/irs/uc1_lin_z_axis_arm_1.json
